export enum ActionType {
  FETCH_POKEMON = "FETCH_POKEMON",
  FETCH_POKEMON_SUCCESS = "FETCH_POKEMON_SUCCESS",
  FETCH_POKEMON_ERROR = "FETCH_POKEMON_ERROR",
  SET_FILTER = "SET_FILTER",
  SET_SELECTED_POKEMON = "SET_SELECTED_POKEMON",
}
